IMT 2200 - Introducción a Ciencia de Datos<br>
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Semestre 2025-S2**<br>
**Profesor:** Rodrigo A. Carrasco <br>

---

## Tarea 01 – Cargando y Analizando Datos

- **Fecha de Entrega:** martes 26 de agosto de 2025, a las 23:59.
- 
**Formato de entrega:** Notebook ejecutado y comentado (`.ipynb`) en l emódulo de Tara 01 habilitado en Canvas.

## Instrucciones

- Esta Tarea debe desarrollarse de manera totalmente *individual*, de acuerdo a lo establecido en la sección de Integridad Académica en el programa del curso.
- La Tarea debe ser desarrollada en lenguaje de programación Python y la entrega en formato Jupyter Notebook.
- El desarrollo del Notebook debe ser claro y ordenado, incluyendo anotaciones (markdown) y comentarios que permitan seguir fácilmente el código y los pasos implementados a los correctores, y siguiendo buenas prácticas de programación. La presentación y claridad del notebook y código forman parte de la evaluación de la tarea.
- Notebook **autocontenible** que:
   - Ejecute sin errores todas las celdas.
  - Contenga tanto el código como los comentarios y explicaciones necesarias.
  - Incluya visualizaciones claras y correctamente etiquetadas.
- No se aceptarán notebooks con celdas rotas o que dependan de rutas externas no indicadas en la tara.

- Deben hacer sus consultas y comentarios sobre la Tarea a traves del canal de Tareas en eo del curso en Canvas.os.
cteriza.

## 1. Objetivos

- Aplicar los conceptos iniciales de manejo de datos y análisis exploratorio vistos en clases.
- Practicar la lectura, limpieza y manipulación de datos en Python.
- Desarrollar habilidades para visualizar y describir patrones y tendencias en conjuntos de datos reales.
- Fomentar la capacidad de comunicar resultados de forma clara y fundamentada.

### 1.1 Objetivo educacional

Esta Tarea tiene como objetivo que los estudiantes desarrollen la capacidad de manejar algunas de las librerías centrales para el desarrollo de Ciencia de Datos, con foco en la lectura y exploración de datos. 

Para los ejercicios a continuación, usted deberá leer, inspeccionar, manipular y graficar conjuntos de datos en distintos formatos, de manera de responder las preguntas de cada parte de la Tarea.

### 1.2 Pregunta de ciencia de datos

Para esta tarea, tendremos como objetivo comprender cómo han cambiado los juegos de mesa en los últimos 40 años. Específicamente queremos saber qué tipos de juegos se han vuelto más comunes hoy en día y qué los caracteriza.

### 1.3 Recomendaciones
- Utiliza las librerías sugeridas en el notebook o justifica brevemente si incorporas otras.
- Revisa que todas las celdas se ejecuten en orden, desde el inicio, sin errores.
- Comenta tu código para explicar qué hace cada sección relevante.
- Asegúrate de que las visualizaciones sean fáciles de interpretar y tengan títulos y etiquetas adecuados.

## 2. Datos

Estaremos utilizando información extraída desde [BoardGameGeek.com](https://boardgamegeek.com/), una plataforma para aficionados de los juegos de mesa, que permite a sus usuarios registrar, calificar e intercambiar sus juegos favoritos. Actualmente, BGG es una de las bases de datos más extensa y diversa de juegos de mesa.

El dataset con el que trabajaremos consiste en un grupo de archivos CSV que contienen información sobre más de 100.000 juegos de mesa almacenados en la plataforma. Este puede descargarse directamente desde el siguiente enlace: https://www.kaggle.com/datasets/mshepherd/board-games Para descargar los datos, haga click en el botón de **Download**, donde podrá descargar los archivos como `.zip`, o bien utilizar la API de Kaggle.

Para el desarrollo de esta tarea, solo utilizaremos los archivos con el prefijo `bgg_`.

**Si utiliza la API de Kaggle para descargar los datos, deje el código utilizado en la siguiente celda:**

In [3]:
# Descarga de datos desde Kaggle
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mshepherd/board-games")

print("Path to dataset files:", path)

c:\Users\lchicao\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\lchicao\.cache\kagglehub\datasets\mshepherd\board-games\versions\13

Copie todo los archivos y los deje en una carpeta llamada 'data'

### 2.1 Librerías

Para esta tarea recomendamos al menos usar las librerías indicadas en la siguiente celda del Notebook. Puede agregar otras si lo estima conveniente para responder de mejor forma las preguntas de la Tarea.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 3. Desarrollo

Para cada una de las siguientes preguntas o actividades incluya una o más celdas de código y Markdown con las respuestas o comentarios necesarios para contestar la pregunta o lograr la actividad. Agregue sus celdas a continuación de cada pregunta para que el Notebook quede ordenado.

En el caso de gráficos, figuras o tablas, asegúrese que todas tengan título, etiquetas en los ejes o haya claridad de los contenidos.

In [2]:
%pwd

'c:\\GIT HUB DESKO\\IMT2200-Lucas-Chicao\\Tareas\\Tarea 1'

In [3]:
%cd data

c:\GIT HUB DESKO\IMT2200-Lucas-Chicao\Tareas\Tarea 1\data

In [6]:
%cd ..

c:\GIT HUB DESKO\IMT2200-Lucas-Chicao\Tareas\Tarea 1

In [4]:
%ls

 Volume in drive C has no label.
 Volume Serial Number is 9E56-4120

 Directory of c:\GIT HUB DESKO\IMT2200-Lucas-Chicao\Tareas\Tarea 1\data

08/18/2025  06:17 PM    <DIR>          .
08/18/2025  06:17 PM    <DIR>          ..
08/15/2025  04:24 PM        18,733,436 bga_GameItem.csv
08/15/2025  04:24 PM             1,532 bgg_Category.csv
08/15/2025  04:24 PM           169,033 bgg_GameFamily.csv
08/15/2025  04:24 PM        16,076,821 bgg_GameItem.csv
08/15/2025  04:24 PM               218 bgg_GameType.csv
08/15/2025  04:24 PM             4,427 bgg_Mechanic.csv
08/15/2025  04:24 PM         1,161,855 bgg_Person.csv
08/15/2025  04:24 PM           596,420 bgg_Publisher.csv
08/15/2025  04:24 PM           586,441 dbpedia_GameItem.csv
08/15/2025  04:24 PM         3,452,968 luding_GameItem.csv
08/15/2025  04:24 PM           801,632 spielen_GameItem.csv
08/15/2025  04:24 PM           542,338 wikidata_GameItem.csv
              12 File(s)     42,127,121 bytes
               2 Dir(s)  57,784,102,912 bytes free

### 3.1 DataFrame unificado (1 punto)

Vamos a cargar en un DataFrame los datos de juegos guardados en el documento `bgg_GameItem.csv`. Al inspeccionar nuestros datos, podemos notar que los valores de ciertas comunas vienen "codificados" con ID. Para comenzar, vamos a juntar la información de los distintos archivos descargados.

**a) (0.8 pts)** Genere un DataFrame único con toda la información de cada juego, incluyendo: nombres de artistas y diseñadores involucrados, mecánicas, categorías, tipo, familia y editorial. Guarde este DataFrame en un nuevo archivo CSV.

In [5]:
# Desarrollo

# bgg_id,               #bgg_id
# name,
# year,
# game_type,            #tipo
# designer,             #Diseñadores          # AAAA
# artist,               #Artistas             # AAAA
# publisher,            #Editorial
# min_players,
# max_players,
# min_players_rec,
# max_players_rec,
# min_players_best,
# max_players_best,
# min_age,min_age_rec,
# min_time,max_time,
# category,             #Categorias
# mechanic,             #Mecanicas
# cooperative,
# compilation,
# compilation_of,
# family,               #Familia
# implementation,
# integration,
# rank,num_votes,
# avg_rating,
# stddev_rating,
# bayes_rating,
# complexity,
# language_dependency,
# bga_id,               #bga_id
# dbpedia_id,           #dbpedia_id
# luding_id,            #luding_id
# spielen_id,           #spielen_id
# wikidata_id,          #wikidata_id
# wikipedia_id          #wikipedia_id

# nombres de artistas - artist
# diseñadores involucrados - designer
# mecánicas - mechanic
# categorías - category 
# tipo    - game_type
# familia - family
# editorial. - publisher

In [49]:
df = pd.read_csv("bgg_GameItem.csv")
person_csv = pd.read_csv("bgg_Person.csv") #artist y designer
#designer_csv = pd.read_csv("bgg_")
mechanic_csv = pd.read_csv("bgg_Mechanic.csv")
category_csv = pd.read_csv("bgg_Category.csv")
gametype_csv = pd.read_csv("bgg_GameType.csv")
family_csv = pd.read_csv("bgg_GameFamily.csv")
publisher_csv = pd.read_csv("bgg_Publisher.csv")


lista_atributos = ["bgg_id","artist", "designer", "mechanic", "category", "game_type", "family", "publisher"]

df_filtrao = df[lista_atributos]


artistas_id = df_filtrao["artist"]
designer_id = df_filtrao["designer"]
mechanic_id = df_filtrao["mechanic"]
category_id = df_filtrao["category"]
game_type_id = df_filtrao["game_type"]
family_id = df_filtrao["family"]
publisher_id = df_filtrao["publisher"]

df_filtrao.head()

,bgg_id,artist,designer,mechanic,category,game_type,family,publisher
0,1,"12517,4959",1,"2916,2080,2012,2072,2040,2020","1021,1026,1001",5497,"10643,34116,91","133,2,24883,2726,15108,39249,11652,5382,8147"
1,2,12424,8384,2009,"1002,1010",5497,"73592,7005,75454","64,20"
2,3,11883,2,"2080,2040,2026,2846,2004,2002","1009,1035",5497,"64960,10634,70711,60111,42,28732","17,133,267,29,7340,7335,41,2973,4617,1391,8291..."
3,4,2277,8008,"2001,2080,2012,2004",1050,5497,"64229,6471,11505",37
4,5,"12658,18317",4,"2040,2910,2900,2940,2005,2002,2874","1021,1086",5497,"78494,4891","92,5,4871,3082,858,2962,28072,5392,4668,38,462..."

In [53]:

artista_id_lista = []

for i in artistas_id:
    i = str(i).split(",")
    artista_id_lista.append(i)

designer_id_lista = []

for i in designer_id:
    i = str(i).split(",")
    designer_id_lista.append(i)

mechanic_id_lista = []

for i in mechanic_id:
    i = str(i).split(",")
    mechanic_id_lista.append(i)

category_id_lista = []

for i in category_id:
    i = str(i).split(",")
    category_id_lista.append(i)

game_type_id_lista = []

for i in game_type_id:
    i = str(i).split(",")
    game_type_id_lista.append(i)

family_id_lista = []

for i in family_id:
    i = str(i).split(",")
    family_id_lista.append(i)

publisher_id_lista = []

for i in publisher_id:
    i = str(i).split(",")
    publisher_id_lista.append(i)

In [55]:
artista_id_lista

[['12517', '4959'],
 ['12424'],
 ['11883'],
 ['2277'],
 ['12658', '18317'],
 ['5'],
 ['36624'],
 ['36807'],
 ['74'],
 ['74', '9'],
 ['28004',
  '44242',
  '12035',
  '11507',
  '11901',
  '65041',
  '308',
  '12123',
  '4959',
  '24642',
  '74',
  '12024',
  '10',
  '233',
  '12102',
  '11883',
  '12038'],
 ['20789', '139382', '64844', '106255', '11883'],
 ['12036',
  '12382',
  '13034',
  '5442',
  '26874',
  '4959',
  '11825',
  '24191',
  '25612',
  '11883',
  '12063'],
 ['6815', '37332', '17547'],
 ['12369', '27686', '779', '13327', '35334', '15161'],
 ['24191', '27879'],
 ['27379',
  '15492',
  '1038',
  '616',
  '13444',
  '18283',
  '6815',
  '127',
  '12009',
  '280',
  '13285',
  '28039'],
 ['12500', '28513', '616', '14508', '18431', '28512', '11883', '18317'],
 ['35234', '11883'],
 ['17'],
 ['nan'],
 ['20202', '20475', '19', '319', '1158'],
 ['677', '7271', '98'],
 ['18088'],
 ['18088', '21'],
 ['12257', '11872'],
 ['nan'],
 ['28060',
  '3737',
  '22153',
  '12003',
  '11177',
  '15956',
  '15323',
  '12004',
  '403',
  '15958',
  '12005'],
 ['17603'],
 ['12424'],
 ['16414'],
 ['111611', '39889'],
 ['13771'],
 ['4769', '31983'],
 ['13910'],
 ['11801', '3106'],
 ['13887'],
 ['19428', '13327'],
 ['11507', '50716', '57603', '127351', '2946', '103901', '12895', '12567'],
 ['12176', '26009', '74', '16910', '44542', '12063'],
 ['28273'],
 ['12597', '11901'],
 ['45736', '4177', '44835', '78608', '12904', '12317', '47211', '12905'],
 ['14642', '12130', '79', '11883'],
 ['12107', '11883'],
 ['11883'],
 ['11883'],
 ['12130', '26874', '22516', '22515', '11902', '11883'],
 ['11883'],
 ['13678',
  '36900',
  '9163',
  '16414',
  '12497',
  '15556',
  '1657',
  '13893',
  '14028',
  '15011',
  '14949'],
 ['nan'],
 ['18700', '38196', '14142', '11883'],
 ['62425'],
 ['3'],
 ['36691',
  '16376',
  '20086',
  '11968',
  '8452',
  '74',
  '11902',
  '98',
  '13160',
  '46',
  '16474'],
 ['11883'],
 ['11845'],
 ['11883'],
 ['9163', '979', '9170', '9379', '15479'],
 ['43315', '693'],
 ['22066', '22084', '46292'],
 ['40163'],
 ['855'],
 ['55'],
 ['11872', '20649', '140'],
 ['nan'],
 ['11883'],
 ['22241', '2652', '71', '17672', '12252', '58'],
 ['59'],
 ['962', '11800', '34863'],
 ['6815'],
 ['61', '15563', '16874', '280'],
 ['11872', '140'],
 ['3414'],
 ['3414'],
 ['nan'],
 ['3414'],
 ['3414'],
 ['68', '68731', '3414'],
 ['nan'],
 ['3414'],
 ['11887', '11825', '11883'],
 ['71', '140'],
 ['nan'],
 ['2652', '23441', '71', '140'],
 ['74'],
 ['11883'],
 ['74'],
 ['nan'],
 ['nan'],
 ['71090'],
 ['nan'],
 ['23114', '51992'],
 ['27899'],
 ['11858', '11872', '34577', '98', '1158'],
 ['nan'],
 ['12519', '12033', '12034', '20625', '32008', '20628', '11872', '885'],
 ['26009', '148884', '37367'],
 ['nan'],
 ['12605'],
 ['11902'],
 ['38280', '4959'],
 ['13976', '11883'],
 ['79', '7483', '20664', '12019', '12017', '121193', '35766', '78938'],
 ['142247', '114330', '108040'],
 ['65861'],
 ['13976'],
 ['12012', '11803'],
 ['73214', '11902'],
 ['16908',
  '96304',
  '104188',
  '11858',
  '13034',
  '115623',
  '37840',
  '99444',
  '99446',
  '99445',
  '99443',
  '35684'],
 ['16531', '14596', '12589', '24858', '14106', '22713', '11883'],
 ['92100', '12382', '30844', '26874', '92101', '12514'],
 ['12261', '11801', '12433', '12434', '667', '12432', '1158'],
 ['13034', '5442', '13245', '11883', '12063'],
 ['3'],
 ['74'],
 ['11997', '37741', '11883'],
 ['nan'],
 ['1038', '11872'],
 ['12828', '56860', '11883', '41897'],
 ['85375', '1038', '23115'],
 ['11883'],
 ['11827'],
 ['22516', '22515', '11902'],
 ['28228', '11883'],
 ['11901'],
 ['557', '56049', '53833', '28548', '2098'],
 ['11801'],
 ['55897', '55898', '9019', '55900', '55901', '55899', '55902', '120566'],
 ['74'],
 ['11883'],
 ['58084'],
 ['74'],
 ['3'],
 ['28043', '11478'],
 ['68048'],
 ['12832'],
 ['5'],
 ['11883', '94'],
 ['74'],
 ['11883'],
 ['99'],
 ['1586'],
 ['28585'],
 ['12516', '92893', '13695', '36237'],
 ['15493', '3737', '33223', '46'],
 ['72437'],
 ['61', '13285'],
 ['3106'],
 ['13335'],
 ['74'],
 ['27689',
  '18349',
  '6422',
  '13034',
  '75103',
  '12673',
  '1261',
  '21797',
  '36237',
  '23115'],
 ['12383'],
 ['28022', '1624', '6206', '4093', '11507', '12673'],
 ['52009',
  '50957',
  '125079',
  '84535',
  '137391',
  '137390',
  '84534',
  '88104',
  '9393',
  '15188'],
 ['75012',
  '119788',
  '122974',
  '11478',
  '141786',
  '119789',
  '111373',
  '80187',
  '133024',
  '91812',
  '90478',
  '12895'],
 ['2954', '27903', '21629', '17672'],
 ['59'],
 ['44242', '3919', '12024', '46292', '40000', '36697'],
 ['280'],
 ['9393'],
 ['11883'],
 ['2946'],
 ['3'],
 ['12705', '12013', '12014', '11883'],
 ['33307'],
 ['94457'],
 ['nan'],
 ['33954', '70252'],
 ['12382'],
 ['74'],
 ['103163', '102462', '12024', '213', '46002'],
 ['11797'],
 ['43471'],
 ['nan'],
 ['12118', '22568', '18529', '2652', '64089'],
 ['231'],
 ['37333', '12905'],
 ['65633', '67458', '23114', '108613', '35684'],
 ['855', '11883'],
 ['12382', '22516', '22515', '855', '11902'],
 ['199', '200'],
 ['nan'],
 ['74', '64844', '74499'],
 ['144011', '12652'],
 ['3'],
 ['12895'],
 ['nan'],
 ['20762'],
 ['11901', '37392'],
 ['107085',
  '98418',
  '12118',
  '3025',
  '74074',
  '172',
  '14057',
  '28066',
  '11883'],
 ['12081', '12588', '12017', '11989'],
 ['17728', '36638', '11797'],
 ['78124', '23319'],
 ['3919'],
 ['38917',
  '98717',
  '12705',
  '111611',
  '11478',
  '75070',
  '12714',
  '11997',
  '12024',
  '12038'],
 ['17124'],
 ['12024'],
 ['962', '57201', '30159'],
 ['27337', '121', '27996', '58786'],
 ['nan'],
 ['nan'],
 ['28039'],
 ['74'],
 ['2652', '12422', '12423'],
 ['12257', '11872'],
 ['79', '17672', '80'],
 ['20431', '11858', '20430', '84542', '11872', '140', '100144', '38138'],
 ['18858', '2652', '12422'],
 ['42845'],
 ['1030'],
 ['60355',
  '28022',
  '52766',
  '63801',
  '12019',
  '12065',
  '11872',
  '12422',
  '14276',
  '1000',
  '63802'],
 ['27907', '36897'],
 ['16468', '1455', '2604', '70483', '22071', '11968', '36651', '11902'],
 ['11857', '2652', '71'],
 ['20473', '29870', '1158'],
 ['nan'],
 ['74'],
 ['13910', '9163', '12428', '70682'],
 ['11933', '22514'],
 ['11872'],
 ['1030'],
 ['22806', '2652', '12422'],
 ['1030', '43738'],
 ['11883'],
 ['148568', '61', '79325', '16872'],
 ['44171', '57163', '35774', '122', '11846'],
 ['17637', '20628', '11872', '110380'],
 ['nan'],
 ['11883'],
 ['11883'],
 ['2652', '12422'],
 ['12011', '78139', '37676', '23483', '12038'],
 ['nan'],
 ['28356'],
 ['nan'],
 ['35026', '28100', '37347'],
 ['37667', '74'],
 ['nan'],
 ['12257'],
 ['nan'],
 ['5249'],
 ['19996', '52259', '962', '12736', '11902'],
 ['12382', '13034', '5442', '26874', '25612', '11', '11883', '12063'],
 ['61'],
 ['11883'],
 ['183', '99965', '30867'],
 ['3306', '18597'],
 ['2652'],
 ['1256', '3347'],
 ['12261', '181', '20628', '110380'],
 ['41021', '29870', '11872'],
 ['35029'],
 ['nan'],
 ['22084'],
 ['37484', '6815'],
 ['4093'],
 ['12831', '67437'],
 ['27641', '144'],
 ['11888'],
 ['64204', '17'],
 ['11883'],
 ['100318'],
 ['11883'],
 ['1333', '24542'],
 ['6815', '11883'],
 ['28005', '12237'],
 ['74499', '11883', '11788'],
 ['855'],
 ['11883'],
 ['75070', '11883'],
 ['12261', '18858'],
 ['1586'],
 ['43702', '12958', '43703'],
 ['1158'],
 ['27907', '36897'],
 ['249', '92233', '11883', '35740'],
 ['7', '11883'],
 ['nan'],
 ['133556'],
 ['3034', '10384', '17825', '9393'],
 ['11883'],
 ['nan'],
 ['72650'],
 ['3', '67649'],
 ['2946', '53973'],
 ['11883'],
 ['28548'],
 ['16579'],
 ['nan'],
 ['3'],
 ['2652', '12422', '661'],
 ['9163', '16414', '12428', '12440'],
 ['11883'],
 ['nan'],
 ['nan'],
 ['3'],
 ['nan'],
 ['11883', '50716', '144001', '75070', '126762'],
 ['11800', '32564'],
 ['nan'],
 ['74'],
 ['28548'],
 ['50009', '11883'],
 ['35234'],
 ['nan'],
 ['nan'],
 ['962', '12386'],
 ['11902'],
 ['11883'],
 ['76341', '72258'],
 ['12653', '12017', '11989'],
 ['11901', '11883'],
 ['11883'],
 ['11883'],
 ['9019', '126814', '11883'],
 ['54057', '7387', '11795'],
 ['nan'],
 ['99725', '30844', '11883'],
 ['18535'],
 ['11883'],
 ['27881', '74'],
 ['28068'],
 ['7'],
 ['nan'],
 ['11478', '33724'],
 ['nan'],
 ['26009', '37367'],
 ['18051', '45899', '18050', '123923'],
 ['nan'],
 ['37377', '37088'],
 ['72517'],
 ['855'],
 ['nan'],
 ['nan'],
 ['1624', '13695'],
 ['nan'],
 ['nan'],
 ['11901', '114459', '43001', '11788'],
 ['nan'],
 ['5312', '28023'],
 ['59341', '12654'],
 ['13849', '17324', '11845'],
 ['24191'],
 ['176'],
 ['37364'],
 ['616', '18283', '45544', '14644', '280'],
 ['13649'],
 ['26874', '22516', '22515', '11902'],
 ['962'],
 ['19562',
  '20015',
  '13767',
  '15141',
  '20016',
  '1475',
  '30810',
  '28381',
  '14560',
  '19977',
  '14541',
  '11989',
  '11988',
  '11990'],
 ['35026', '150190', '123923'],
 ['nan'],
 ['33306', '53971', '12657', '12565'],
 ['nan'],
 ['11883'],
 ['11847'],
 ['nan'],
 ['1463'],
 ['12591'],
 ['nan'],
 ['nan'],
 ['12121'],
 ['17742', '36697'],
 ['nan'],
 ['4476'],
 ['11883'],
 ['nan'],
 ['12516', '12193', '2652', '13649', '13456'],
 ['928'],
 ['27910', '21797', '23115'],
 ['27910', '21797', '23115'],
 ['nan'],
 ['12261', '71', '12252', '667'],
 ['3'],
 ['11883'],
 ['43327', '43328', '3030'],
 ['30281', '30280'],
 ['962', '11800'],
 ['102034', '44835', '35690', '65231', '11883'],
 ['22512', '22513', '12565'],
 ['11883'],
 ['11883'],
 ['27901', '12872'],
 ['12830', '12620', '11883', '41897', '77322', '16880'],
 ['nan'],
 ['15016'],
 ['34291'],
 ['68048', '3030'],
 ['37200', '44242', '37201', '11883'],
 ['49954', '8577'],
 ['nan'],
 ['nan'],
 ['3'],
 ['28010', '28270'],
 ['12823'],
 ['74'],
 ['74'],
 ['nan'],
 ['34275'],
 ['nan'],
 ['36802', '250'],
 ['nan'],
 ['74'],
 ['76846',
  '40174',
  '41753',
  '14753',
  '49922',
  '13924',
  '16448',
  '49894',
  '13376',
  '43829',
  '13641',
  '13375',
  '29182',
  '17124',
  '14681',
  '13518',
  '29183',
  '13948',
  '12036',
  '29184',
  '13419',
  '29185',
  '29186',
  '13832',
  '15963',
  '29187',
  '19565',
  '14936',
  '13631',
  '12827',
  '19627',
  '29189',
  '13306',
  '12503',
  '14761',
  '41134',
  '29190',
  '13794',
  '12497',
  '19412',
  '13632',
  '41752',
  '50887',
  '29191',
  '14417',
  '29192',
  '29193',
  '15492',
  '29194',
  '16052',
  '29195',
  '3330',
  '40178',
  '19411',
  '38001',
  '22772',
  '13737',
  '14425',
  '49412',
  '29287',
  '13526',
  '15314',
  '14642',
  '130341',
  '19612',
  '43247',
  '41755',
  '29288',
  '13241',
  '14268',
  '29289',
  '29290',
  '15024',
  '26712',
  '14287',
  '41877',
  '12511',
  '40182',
  '13343',
  '14765',
  '15223',
  '15464',
  '29293',
  '13455',
  '29916',
  '29917',
  '2092',
  '15019',
  '29918',
  '15135',
  '14648',
  '21006',
  '12509',
  '13718',
  '29920',
  '40243',
  '29927',
  '12096',
  '29964',
  '29965',
  '13485',
  '14657',
  '29966',
  '15121',
  '33547',
  '13312',
  '24690',
  '6071',
  '11994',
  '19567',
  '9234',
  '1038',
  '50031',
  '16051',
  '29967',
  '14937',
  '14611',
  '61',
  '29968',
  '15054',
  '50027',
  '29970',
  '13797',
  '29972',
  '14861',
  '29973',
  '14291',
  '21583',
  '14699',
  '29975',
  '15504',
  '18043',
  '616',
  '33437',
  '14889',
  '16619',
  '14049',
  '13089',
  '18175',
  '40189',
  '40190',
  '49899',
  '16447',
  '9859',
  '15020',
  '26864',
  '40192',
  '14508',
  '17517',
  '15560',
  '14762',
  '17298',
  '16463',
  '16637',
  '21333',
  '43708',
  '14763',
  '20339',
  '16336',
  '14947',
  '13325',
  '19922',
  '40198',
  '15008',
  '14939',
  '49930',
  '40199',
  '16294',
  '14445',
  '14733',
  '15806',
  '50032',
  '14862',
  '40203',
  '12443',
  '49851',
  '40216',
  '25640',
  '12233',
  '14946',
  '14232',
  '14231',
  '50034',
  '40218',
  '40219',
  '25255',
  '13949',
  '12012',
  '33326',
  '13630',
  '26040',
  '14202',
  '40221',
  '11884',
  '25804',
  '14959',
  '13634',
  '40222',
  '30016',
  '21806',
  '49895',
  '40224',
  '40225',
  '40242',
  '28288',
  '19878',
  '14953',
  '12019',
  '40228',
  '40229',
  '40230',
  '40231',
  '40232',
  '40234',
  '13635',
  '39597',
  '40235',
  '39876',
  '19686',
  '40237',
  '14616',
  '40248',
  '40249',
  '40250',
  '28138',
  '14745',
  '16455',
  '40252',
  '15935',
  '13636',
  '13637',
  '14756',
  '14446',
  '41751',
  '17160',
  '40260',
  '33097',
  '12534',
  '14525',
  '14792',
  '24244',
  '17763',
  '40263',
  '18931',
  '21498',
  '14825',
  '13920',
  '40305',
  '13990',
  '19475',
  '31445',
  '40309',
  '13379',
  '31500',
  '24402',
  '14299',
  '29346',
  '19569',
  '40313',
  '41754',
  '13452',
  '33025',
  '14950',
  '17306',
  '40316',
  '15368',
  '15537',
  '21427',
  '13413',
  '14757',
  '14940',
  '40317',
  '17057',
  '14109',
  '40318',
  '31983',
  '21761',
  '12502',
  '15563',
  '14047',
  '13896',
  '27196',
  '40321',
  '1657',
  '16674',
  '49850',
  '15805',
  '13950',
  '13638',
  '12501',
  '15225',
  '18781',
  '5249',
  '14302',
  '17323',
  '5211',
  '14635',
  '40324',
  '40325',
  '15220',
  '39678',
  '40328',
  '16451',
  '20578',
  '40329',
  '486',
  '18929',
  '40330',
  '14316',
  '13951',
  '5318',
  '49388',
  '19348',
  '13979',
  '49870',
  '14097',
  '19538',
  '40333',
  '13976',
  '50030',
  '40334',
  '50023',
  '28793',
  '19806',
  '29291',
  '21995',
  '40656',
  '14239',
  '35766',
  '41875',
  '14317',
  '24268',
  '10548',
  '41876',
  '885',
  '15025',
  '14106',
  '20577',
  '15843',
  '17518',
  '40339',
  '12090',
  '14585',
  '40340',
  '14704',
  '14960',
  '14976',
  '14625',
  '13418',
  '14758',
  '15929',
  '14348',
  '19664',
  '14737',
  '40344',
  '11803',
  '40345',
  '17472',
  '25506',
  '40347',
  '14278',
  '40348',
  '13063',
  '16659',
  '17256',
  '14855',
  '40349',
  '14075',
  '12316',
  '40350',
  '14705',
  '15517',
  '27508',
  '13983',
  '13326',
  '40351',
  '15100',
  '4087',
  '12086',
  '34343',
  '15449',
  '15016',
  '40355',
  '17970',
  '16872',
  '40357',
  '14961',
  '15546',
  '9373',
  '41872',
  '19127',
  '49892',
  '14076',
  '40361',
  '49932',
  '40362',
  '40363',
  '40364',
  '13234',
  '14337',
  '35624',
  '17109',
  '18391',
  '40233',
  '12495',
  '14449',
  '280',
  '40368',
  '40369',
  '15026',
  '12651',
  '40370',
  '19631',
  '16234',
  '14349',
  '40372',
  '40373',
  '18624',
  '14900',
  '18258',
  '14284',
  '14679',
  '14685',
  '19413',
  '40379',
  '40380',
  '25737',
  '40383',
  '40382',
  '40384',
  '49893',
  '15011',
  '15329',
  '15043',
  '14719',
  '13711',
  '15144',
  '15012',
  '29225',
  '40388',
  '40389',
  '14759',
  '40392',
  '15018',
  '12593',
  '17551',
  '1427',
  '12080',
  '40395',
  '24115',
  '13610',
  '19805',
  '40397',
  '12269',
  '40398',
  '11883',
  '43820',
  '41873',
  '14978',
  '14949',
  '19435',
  '15197',
  '40401',
  '14764',
  '40402',
  '13412',
  '16192',
  '14760',
  '40404',
  '40405',
  '40406',
  '13199',
  '23763',
  '24739',
  '22395',
  '14957',
  '49861',
  '19062',
  '1857',
  '14443',
  '36526',
  '40410',
  '14691',
  '2582',
  '40413',
  '40411',
  '40412',
  '40414',
  '40415',
  '40416',
  '40417',
  '40419',
  '40418',
  '41874',
  '13243',
  '41756',
  '1208',
  '40421',
  '40422',
  '40423',
  '40424',
  '40425',
  '49934',
  '40426',
  '12296',
  '50690',
  '40427',
  '40428',
  '13456'],
 ['11507', '1586', '11478', '11883'],
 ['37708'],
 ['12058', '143907'],
 ['nan'],
 ['nan'],
 ['28070'],
 ['3025'],
 ['9163',
  '979',
  '12428',
  '12430',
  '779',
  '12488',
  '4802',
  '12429',
  '12431',
  '12427'],
 ['11883'],
 ['15063', '13649'],
 ['80022', '121599', '11883'],
 ['3'],
 ['nan'],
 ['12519',
  '11886',
  '11994',
  '125',
  '18416',
  '11995',
  '1150',
  '11992',
  '11993',
  '12017',
  '107782',
  '21',
  '11989',
  '19965'],
 ['12591'],
 ['nan'],
 ['nan'],
 ['11883'],
 ['28510', '43616', '12130', '17673', '116777', '17672', '21974'],
 ['nan'],
 ['12469', '11883'],
 ['12810', '11901', '12045'],
 ['nan'],
 ['2119', '28586'],
 ['29009', '22516', '22515'],
 ['231'],
 ['11883'],
 ['74'],
 ['34481', '12011', '24189'],
 ['11883'],
 ['40811'],
 ['11883'],
 ['nan'],
 ['nan'],
 ['3106'],
 ['12878'],
 ['11883'],
 ['12508', '80022', '12017', '11989', '11902'],
 ['37145', '233'],
 ['49843'],
 ['61', '20349'],
 ['28485', '37626', '37625', '12472'],
 ['23740', '12251'],
 ['11902'],
 ['11883'],
 ['27884'],
 ['nan'],
 ['nan'],
 ['3'],
 ['nan'],
 ['2809'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['84274', '12965'],
 ['35026', '12736'],
 ['nan'],
 ['nan'],
 ['244', '12605'],
 ['244', '12605'],
 ['11883'],
 ['22514'],
 ['nan'],
 ['36093', '12872', '11804'],
 ['27685', '12912'],
 ['nan'],
 ['245'],
 ['12759'],
 ['nan'],
 ['27612'],
 ['3'],
 ['nan'],
 ['684', '96173'],
 ['20997', '20996'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['779', '22516', '24191', '22515', '12380'],
 ['25', '16431'],
 ['408', '7246', '70041', '108409', '407'],
 ['16480', '6815', '844'],
 ['11902'],
 ['12886', '12011', '7', '81856', '105660', '8', '11883'],
 ['11901'],
 ['11883'],
 ['11902'],
 ['43973', '11883'],
 ['22514'],
 ['11883'],
 ['nan'],
 ['nan'],
 ['11883'],
 ['11883'],
 ['74'],
 ['11901'],
 ['154'],
 ['nan'],
 ['855'],
 ['25390', '10723'],
 ['nan'],
 ['3106'],
 ['nan'],
 ['28423'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['28532', '855'],
 ['nan'],
 ['2652', '71'],
 ['nan'],
 ['222', '16109'],
 ['48865', '92276'],
 ['nan'],
 ['22514'],
 ['65542', '12013'],
 ['6815'],
 ['nan'],
 ['nan'],
 ['59'],
 ['nan'],
 ['140694', '106668'],
 ['11800'],
 ['nan'],
 ['74'],
 ['74'],
 ['12043', '11846'],
 ['nan'],
 ['nan'],
 ['12905'],
 ['nan'],
 ['94857', '3106'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['41403', '132', '12530', '84979', '66790', '120916'],
 ['12257', '20469'],
 ['nan'],
 ['280'],
 ['71'],
 ['281'],
 ['nan'],
 ['52239'],
 ['nan'],
 ['6861'],
 ['nan'],
 ['nan'],
 ['6815', '36828', '27336'],
 ['2954', '14142'],
 ['12383', '17672', '11845'],
 ['65086', '71'],
 ['nan'],
 ['nan'],
 ['11883'],
 ['174'],
 ['nan'],
 ['nan'],
 ['6815'],
 ['6815'],
 ['nan'],
 ['nan'],
 ['53', '43346'],
 ['22084', '12317', '37393'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['12591'],
 ['12596'],
 ['11883'],
 ['42595'],
 ['11883'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['54057'],
 ['27885'],
 ['74694'],
 ['20202', '19', '20204', '20203', '319'],
 ['12252', '1158'],
 ['33104', '18175', '15419', '13114'],
 ['15102'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['1038'],
 ['nan'],
 ['921'],
 ['3'],
 ['3911'],
 ['nan'],
 ['12530', '34823', '78606'],
 ['nan'],
 ['20072', '128424'],
 ['nan'],
 ['6477', '3034', '14759'],
 ['962'],
 ['20532', '15963', '14744', '20533', '15316', '5249', '20534'],
 ['nan'],
 ['15099'],
 ['nan'],
 ['nan'],
 ['979', '125916', '92163', '12498'],
 ['16414'],
 ['335', '7916', '14590', '4769', '11883'],
 ['nan'],
 ['140'],
 ['79'],
 ['nan'],
 ['71', '1030'],
 ['20072', '140'],
 ['140'],
 ['nan'],
 ['46'],
 ['74'],
 ['14937', '12370', '2582'],
 ['14501', '19877', '19484'],
 ['13910', '108498', '979', '12488'],
 ['3585', '11802'],
 ['nan'],
 ['71', '11872', '140'],
 ['12261', '18858', '27337', '2652', '36638'],
 ['27906', '27907'],
 ['13592', '51977'],
 ['nan'],
 ['nan'],
 ['15058', '34863', '13765'],
 ['nan'],
 ['28542', '3347'],
 ['1256', '3347'],
 ['2652', '3095'],
 ['240', '3034', '13540', '13528', '13830'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['11901'],
 ['nan'],
 ['nan'],
 ['44468'],
 ['27891', '20021', '140'],
 ['nan'],
 ['nan'],
 ['2150', '8381'],
 ['1030'],
 ['140'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['22513'],
 ['12072'],
 ['71', '1008'],
 ['nan'],
 ['2652', '12422'],
 ['50458', '59423', '9015'],
 ['nan'],
 ['12358'],
 ['2652', '12422'],
 ['51039', '71', '140'],
 ['280'],
 ['625'],
 ['nan'],
 ['11883'],
 ['3'],
 ['nan'],
 ['11888'],
 ['nan'],
 ['149530',
  '74508',
  '40755',
  '12037',
  '126919',
  '34490',
  '44217',
  '106108',
  '123923',
  '11883',
  '139870'],
 ['nan'],
 ['12878'],
 ['11883'],
 ['37035'],
 ['86'],
 ['11883'],
 ['3'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['93612', '17324', '503'],
 ['nan'],
 ['15161'],
 ['nan'],
 ['nan'],
 ['16468', '2604', '58417', '1038', '24185', '14212', '728'],
 ['24191'],
 ['18535'],
 ['nan'],
 ['nan'],
 ['40821'],
 ['nan'],

In [ ]:
for i in artista_id_lista :
    
    dictsito = {}
    
    if len(i) >= 2:
        print(">=2")
        
        for w in i :
            pass
        
    elif len(i) == 1 :
        print("1")
        
        if i == "nan" :
            pass
        else:
            pass
        
    break

aa

In [54]:
person_csv.head()

   bgg_id                name
0       1  Karl-Heinz Schmiel
1       2       Reiner Knizia
2       3        (Uncredited)
3       4         Sid Sackson
4       5        Jean du Poël

**b) (0.2 pts)** ¿Cuánto espacio en disco ocupa este DataFrame? ¿Cuánto espacio en disco ocupan los documentos CSV separados? ¿A qué se debe esta diferencia? Comente.

### 3.2 Juegos publicados anualmente (1.5 puntos)


**a) (0.5 pts)** Limpie los datos para dejar solo aquellos que tienen valores válidos de año de publicación. Luego responda: ¿cuál es el rango de años con el que estamos trabajando? ¿Tienen sentido estos años?

**b) (0.5 pts)** Seleccione solamente los juegos entre los años 1980 y 2025. Luego grafique la cantidad de juegos publicados por año. ¿Cómo es esta tendencia? Comente.

**c) (0.5 pts)** ¿Entre qué años hubo un mayor aumento de publicación de juegos de mesa según los registros de BGG?

### 3.3 Análisis de duración y complejidad (1.5 puntos)

Si bien hay muchas posibles características que podemos explorar para los juegos de mesa, esta vez nos centraremos en el tiempo de juego y la complejidad. En esta sección queremos comprender si se ha modificado notablemente la duración promedio y la percepción de complejidad de los juegos de mesa a través de los años.

**a) (0.3 pts)** Inspecciones y filtre los datos que tengan valores válidos para: tiempo mínimo de juego, tiempo máximo de juego y complejidad. En el caso de que existan "outliers", puede descartarlos, cosiderando un rango razonable para las variables anteriores. Justifique su desición.

**b) (0.2 pts)** Veremos ahora si ha cambiado la duración promedio de los juegos de mesa en nuestro rango de años seleccionado. Primero, cree una nueva columna `avg_time` en el dataset con la duración promedio supuesta para cada juego.

**c) (0.5 pts)** Grafique la duración promedio de juegos al año entre 1980 y 2025. ¿Existe alguna tendencia? Asegúrese de colocar las unidades correspondientes en sus ejes si es necesario. Comente sus resultados.

**d) (0.5 pts)** Nos interesa saber si los juegos de mesa recientes son más complejos que aquellos publicados antes de los 2000. BoardGameGeek permite evaluar la complejidad (o "weight") de un juego en una escala de 1 a 5, siendo 1 un juego "liviano" o fácil de entender, y 5 un juego "pesado" o complejo. Primero, seleccione los juegos que han sido evaluados por al menos 100 usuarios. Luego grafique la complejidad promedio de los juegos según año. Responda: ¿ha cambiado la percepción de complejidad entre juegos entre 1980 y la actualidad?

### 3.4 Análisis de categorías comunes (2 puntos)

Existe una gran diversidad de categorías de juegos de mesa. Ahora nos concentraremos en un grupo específico de ellas, con el fin de analizar cómo a cambiado la cantidad de juegos de estas clases desde 1980 hasta hoy.

**a) (0.7 pts)** ¿Cuáles son las 5 categorías más comunes en los juegos del dataset? Muestre la cantidad de juegos que hay de cada una. Puede graficar estos valores, o bien, entregar un DataFrame con sus valores.

**b) (0.3 pts)** Para cada una de estas 5 categorías, cree un DataFrame que contenga la cantidad de juegos en el dataset según año. Luego junte estos DataFrames en uno solo con los atributos de "Año", "Categoría" y "Cantidad".

**c) (1 pto)** Grafique, en un solo gráfico y con distintos colores, la cantidad de juegos por año según categoría. Preocúpese de ponerle etiquetas al gráfico para identificar cada categoría y una leyenda donde se muestre cada una. Comente: ¿ha habido un cambio entre los juegos más comunes en los años 80 y hoy?

### 3.5 Análisis Crítico (Bono +0.5 puntos)

¿Qué limitaciones o problemas encontraste en los datos?